# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      env_choice:
        type: choice
        description: Select the environment
        options:
        - uat
        - devint

jobs:
  build:
   # variables:
   #   env_name: test
   #   feature_flag: ''
   # rules:
   # - if: '$env_choice == "uat"'
    #  variables: 
   #     env_name: uat
  #      feature_flag: FEATURE_
 #   - if: '$VAR =~ /pattern/'
#      when: manual
#    - when: on_success
    runs-on: macos-latest
    steps:
      - name: Build
        run: |
        if [ ${env_choice} == "uat" ]; then echo 'normalno'; else echo 'ploho'; fi
